import os
import re
import json
import logging
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build

logger = logging.getLogger(__name__)

SCOPES = ['https://www.googleapis.com/auth/documents']


def get_docs_service():
    """
    Build Google Docs API service using an OAuth token stored in GOOGLE_TOKEN.

    GOOGLE_TOKEN should contain the full JSON contents of the token.json file
    generated by running auth.py locally. Railway stores this as an env var.
    """
    token_raw = os.getenv('GOOGLE_TOKEN')
    if not token_raw:
        raise ValueError(
            "GOOGLE_TOKEN environment variable is not set.\n"
            "Run auth.py locally, then paste the token.json contents into Railway."
        )

    token_info = json.loads(token_raw)
    creds = Credentials.from_authorized_user_info(token_info, SCOPES)

    # Auto-refresh if expired (uses the refresh_token inside the token JSON)
    if creds.expired and creds.refresh_token:
        creds.refresh(Request())
        logger.info("Google OAuth token refreshed.")

    return build('docs', 'v1', credentials=creds)


def _para_text(paragraph: dict) -> str:
    """Extract plain text from a paragraph element."""
    return ''.join(
        el['textRun']['content']
        for el in paragraph.get('elements', [])
        if 'textRun' in el
    )


def get_latest_lesson(doc_id: str) -> dict:
    service = get_docs_service()
    doc = service.documents().get(documentId=doc_id).execute()
    body_content = doc.get('body', {}).get('content', [])

    paragraphs = []
    for element in body_content:
        if 'paragraph' in element:
            text = _para_text(element['paragraph']).strip()
            if text:
                paragraphs.append({
                    'text': text,
                    'start': element.get('startIndex', 0),
                    'end': element.get('endIndex', 0),
                })

    lezione_re = re.compile(r'Lezione\s+\d+', re.IGNORECASE)
    heading_indices = [i for i, p in enumerate(paragraphs) if lezione_re.search(p['text'])]

    if not heading_indices:
        raise ValueError(
            "No lesson headings found in the document.\n"
            "Expected format: __Lezione 39, apr 2__"
        )

    last_idx = heading_indices[0]
    raw_title = paragraphs[last_idx]['text']
    title = re.sub(r'[_*#]', '', raw_title).strip()

    phrase_paras = paragraphs[last_idx + 1:]

    phrases = []
    for para in phrase_paras:
        text = para['text'].strip()
        if not text:
            continue
        if lezione_re.search(text):
            break

        if '==' in text:
            italian = text.split('==')[0].strip()
            if italian:
                phrases.append(italian)
        else:
            phrases.append(text)

    if not phrases:
        raise ValueError(
            f"No phrases found under '{title}'.\n"
            "Make sure phrases follow the heading in the doc."
        )

    logger.info(f"Loaded lesson '{title}' with {len(phrases)} phrases.")
    return {'title': title, 'phrases': phrases}


def append_story_to_doc(
    doc_id: str,
    lesson_title: str,
    story: str,
    translation: str,
    exercises: list[str],
    image_url: str | None = None,
) -> None:
    """
    Appends the generated story, translation, exercises, and image link
    to the end of the Google Doc.
    """
    service = get_docs_service()

    # Fetch current doc to find the end index
    doc = service.documents().get(documentId=doc_id).execute()
    body_content = doc.get('body', {}).get('content', [])
    end_index = body_content[-1]['endIndex'] - 1

    # Build exercises block
    ex_lines = ''.join(f'{i}. {ex}\n' for i, ex in enumerate(exercises, 1))

    # Optional image line
    img_line = f'\n🖼️ Cover image: {image_url}\n' if image_url else ''

    # Full text block to append
    block = (
        '\n\n' + ('─' * 35) + '\n\n'
        f'📖 Storia — {lesson_title}\n'
        f'{img_line}\n'
        f'{story}\n\n'
        f'🇷🇺 Traduzione\n\n'
        f'{translation}\n\n'
        f'📝 Esercizi\n\n'
        f'{ex_lines}'
    )

    service.documents().batchUpdate(
        documentId=doc_id,
        body={
            'requests': [
                {
                    'insertText': {
                        'location': {'index': end_index},
                        'text': block,
                    }
                }
            ]
        }
    ).execute()

    logger.info(f"Story appended to doc {doc_id}.")
